export const theme = {
  name: "DefaultTheme",
  colors: {
    WHITE: "#ffffff",
    BLACK: "#0f0f0f",
    GRAY: "#ececec",
    GRAY_SECONDARY: "#B3B0B8",
    YELLOW: "#cd8d04",
  },
  fonts: {
    Montserrat_Regular: "Montserrat_400Regular",
    Montserrat_Medium: "Montserrat_500Medium",
    Montserrat_SemiBold: "Montserrat_600SemiBold",
    Montserrat_Bold: "Montserrat_700Bold",
  },
  sizes: {
    xxxs: 8,
    xxs: 12,
    xs: 14,
    sm: 16,
    md: 18,
    lg: 20,
    xl: 24,
    xxl: 28,
    xxxl: 32,
  },
  spacing: {
    xxxs: 2,
    xxs: 4,
    xs: 8,
    sm: 12,
    md: 16,
    lg: 20,
    xl: 24,
    xxl: 28,
    xxxl: 32,
  },
};
